import LibraryCard from "@/components/LibraryCard"
import Head from "next/head"
import React from "react"

const library = () => {
  const data = [1, 2, 3, 4]
  return (
    <>
      <Head>
        <title>filFlix | Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h2 className="text-3xl underline text-center mt-8">Your Library</h2>
      <div className="flex flex-wrap justify-center items-center">
        {data.map((i, idx) => (
          <LibraryCard key={idx} />
        ))}
      </div>
    </>
  )
}

export default library
