import LibraryCard from "@/components/LibraryCard"
import { SUBSCRIPTION_LIFETIME_ADDRESS, SUBSCRIPTION_LIFETIME_ADDRESS_ABI } from "@/constants"
import Head from "next/head"
import React, { useEffect, useState } from "react"
import { useAccount, useContractRead } from "wagmi"

const library = () => {
  const [data, setData] = useState(null)
  const [balance, setBalance] = useState(0)
  const { address, isConnecting, isDisconnected } = useAccount()
  const contractRead = useContractRead({
    address: SUBSCRIPTION_LIFETIME_ADDRESS,
    abi: SUBSCRIPTION_LIFETIME_ADDRESS_ABI,
    functionName: "balanceOf",
    args: [address],
  })

  useEffect(() => {
    fetch("/api/discover")
      .then((res) => res.json())
      .then((data) => setData(data))
  })

  useEffect(() => {
    setBalance(contractRead.data)
  }, [contractRead])

  return (
    <>
      <Head>
        <title>filFlix | Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h2 className="text-3xl underline text-center mt-8">Your Library</h2>
      <div className="flex flex-wrap justify-center items-center">
        {balance > 0 ? (
          data && data.map((i) => <LibraryCard key={i._id} props={i} />)
        ) : (
          <h2 className="text-center m-4 text-lg">
            Get the{" "}
            <a className="underline" href="/subscribe">
              subscription
            </a>{" "}
            or{" "}
            <a href="/discover" className="underline">
              buy some content!
            </a>
          </h2>
        )}
      </div>
    </>
  )
}

export default library
